DELETE FROM books;
INSERT INTO books (title, description, date_published, photo)
VALUES
    ('1984', 'The new novel by George Orwell is the major work towards which all his previous writing has pointed. Critics have hailed it as his "most solid, most brilliant" work. Though the story of Nineteen Eighty-Four takes place thirty-five years hence, it is in every sense timely. The scene is London, where there has been no new housing since 1950 and where the city-wide slums are called Victory Mansions. Science has abandoned Man for the State. As every citizen knows only too well, war is peace.

To Winston Smith, a young man who works in the Ministry of Truth (Minitru for short), come two people who transform this life completely. One is Julia, whom he meets after she hands him a slip reading, "I love you." The other is O\'Brien, who tells him, "We shall meet in the place where there is no darkness." The way in which Winston is betrayed by the one and, against his own desires and instincts, ultimately betrays the other, makes a story of mounting drama and suspense','1949-06-08' ,'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781256i/61439040.jpg'),
    ('The Picture of Dorian Gray', 'Oscar Wilde’s only novel is the dreamlike story of a young man who sells his soul for eternal youth and beauty.

In this celebrated work Wilde forged a devastating portrait of the effects of evil and debauchery on a young aesthete in late-19th-century England. Combining elements of the Gothic horror novel and decadent French fiction, the book centers on a striking premise: As Dorian Gray sinks into a life of crime and gross sensuality, his body retains perfect youth and vigor while his recently painted portrait grows day by day into a hideous record of evil, which he must keep hidden from the world. For over a century, this mesmerizing tale of horror and suspense has enjoyed wide popularity. It ranks as one of Wilde\'s most important creations and among the classic achievements of its kind.', '1890-06-01', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546103428i/5297.jpg' ),
    ('Pride and Prejudice','Since its immediate success in 1813, Pride and Prejudice has remained one of the most popular novels in the English language. Jane Austen called this brilliant work "her own darling child" and its vivacious heroine, Elizabeth Bennet, "as delightful a creature as ever appeared in print." The romantic clash between the opinionated Elizabeth and her proud beau, Mr. Darcy, is a splendid performance of civilized sparring. And Jane Austen\'s radiant wit sparkles as her characters dance a delicate quadrille of flirtation and intrigue, making this book the most superb comedy of manners of Regency England.','1813-01-28' , 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1320399351i/1885.jpg'),
    ('The Great Gatsby','The Great Gatsby, F. Scott Fitzgerald\'s third book, stands as the supreme achievement of his career. This exemplary novel of the Jazz Age has been acclaimed by generations of readers. The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession," it is an exquisitely crafted tale of America in the 1920s.

The Great Gatsby is one of the great classics of twentieth-century literature. ','1925-04-10' , 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490528560i/4671.jpg'),
    ('Of Mice and Men', 'They are an unlikely pair: George is "small and quick and dark of face"; Lennie, a man of tremendous size, has the mind of a young child. Yet they have formed a "family," clinging together in the face of loneliness and alienation. Laborers in California\'s dusty vegetable fields, they hustle work when they can, living a hand-to-mouth existence. But George and Lennie have a plan: to own an acre of land and a shack they can call their own.

While the powerlessness of the laboring class is a recurring theme in Steinbeck\'s work of the late 1930s, he narrowed his focus when composing \'Of Mice and Men\' (1937), creating an intimate portrait of two men facing a world marked by petty tyranny, misunderstanding, jealousy, and callousness. But though the scope is narrow, the theme is universal: a friendship and a shared dream that makes an individual\'s existence meaningful.

A unique perspective on life\'s hardships, this story has achieved the status of timeless classic due to its remarkable success as a novel, a Broadway play, and three acclaimed films.', '1937-02-25', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511302904i/890.jpg'),
    ('Fahrenheit 451', 'Sixty years after its original publication, Ray Bradbury’s internationally acclaimed novel Fahrenheit 451 stands as a classic of world literature set in a bleak, dystopian future. Today its message has grown more relevant than ever before.

Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.', '1953-10-19', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1383718290i/13079982.jpg'),
    ('A World of Curiosities', 'Chief Inspector Armand Gamache returns in the eighteenth book in #1 New York Times bestseller Louise Penny\'s beloved series.

It’s spring and Three Pines is reemerging after the harsh winter. But not everything buried should come alive again. Not everything lying dormant should reemerge.

But something has.

As the villagers prepare for a special celebration, Armand Gamache and Jean-Guy Beauvoir find themselves increasingly worried. A young man and woman have reappeared in the Sûreté du Québec investigators’ lives after many years. The two were young children when their troubled mother was murdered, leaving them damaged, shattered. Now they’ve arrived in the village of Three Pines.', '2022-11-29', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1660936424i/60899502.jpg'),
    ('Horse', 'Kentucky, 1850. An enslaved groom named Jarret and a bay foal forge a bond of understanding that will carry the horse to record-setting victories across the South. When the nation erupts in civil war, an itinerant young artist who has made his name on paintings of the racehorse takes up arms for the Union. On a perilous night, he reunites with the stallion and his groom, very far from the glamor of any racetrack.

New York City, 1954. Martha Jackson, a gallery owner celebrated for taking risks on edgy contemporary painters, becomes obsessed with a nineteenth-century equestrian oil painting of mysterious provenance.

Washington, DC, 2019. Jess, a Smithsonian scientist from Australia, and Theo, a Nigerian-American art historian, find themselves unexpectedly connected through their shared interest in the horse--one studying the stallion\'s bones for clues to his power and endurance, the other uncovering the lost history of the unsung Black horsemen who were critical to his racing success.

Based on the remarkable true story of the record-breaking thoroughbred Lexington, Horse is a novel of art and science, love and obsession, and our unfinished reckoning with racism.', '2022-06-14', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1639948376i/59109077.jpg'),
    ('The Cloisters', 'When Ann Stilwell arrives in New York City, she expects to spend her summer working as a curatorial associate at the Metropolitan Museum of Art. Instead, she finds herself assigned to The Cloisters, a gothic museum and garden renowned for its medieval art collection and its group of enigmatic researchers studying the history of divination.

Desperate to escape her painful past, Ann is happy to indulge the researchers’ more outlandish theories about the history of fortune telling. But what begins as academic curiosity quickly turns into obsession when Ann discovers a hidden 15th-century deck of tarot cards that might hold the key to predicting the future. When the dangerous game of power, seduction, and ambition at The Cloisters turns deadly, Ann becomes locked in a race for answers as the line between the arcane and the modern blurs.', '2022-11-01', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1667414469i/61054804.jpg'),
    ('Now Is Not the Time to Panic', 'From the New York Times bestselling author of Nothing to See Here comes an exuberant, bighearted novel about two teenage misfits who spectacularly collide one fateful summer, and the art they make that changes their lives forever.

Sixteen-year-old Frankie Budge—aspiring writer, indifferent student, offbeat loner—is determined to make it through yet another sad summer in Coalfield, Tennessee, when she meets Zeke, a talented artist who has just moved into his grandmother’s unhappy house and who is as lonely and awkward as Frankie is. Romantic and creative sparks begin to fly, and when the two jointly make an unsigned poster, shot through with an enigmatic phrase, it becomes unforgettable to anyone who sees it. The edge is a shantytown filled with gold seekers. We are fugitives, and the law is skinny with hunger for us.', '2022-11-15', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1673009807i/60415700.jpg'),
    ('Signal Fires', 'SIGNAL FIRES opens on a summer night in 1985. Three teenagers have been drinking. One of them gets behind the wheel of a car, and, in an instant, everything on Division Street changes. Each of their lives, and that of Ben Wilf, a young doctor who arrives on the scene, is shattered. For the Wilf family, the circumstances of that fatal accident will become the deepest kind of secret, one so dangerous it can never be spoken.

On Division Street, time has moved on. When the Shenkmans arrive—a young couple expecting a baby boy—it is as if the accident never happened. But when Waldo, the Shenkmans’ brilliant, lonely son who marvels at the beauty of the world and has a native ability to find connections in everything, befriends Dr. Wilf, now retired and struggling with his wife’s decline, past events come hurtling back in ways no one could ever have foreseen.

In Dani Shapiro’s first work of fiction in fifteen years, she returns to the form that launched her career, with a riveting, deeply felt novel that examines the ties that bind families together—and the secrets that can break them apart. SIGNAL FIRES is a work of haunting beauty by a masterly storyteller.', '2022-10-18', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1648606891i/59573299.jpg'),
    ('Normal People', 'At school Connell and Marianne pretend not to know each other. He’s popular and well-adjusted, star of the school soccer team while she is lonely, proud, and intensely private. But when Connell comes to pick his mother up from her housekeeping job at Marianne’s house, a strange and indelible connection grows between the two teenagers - one they are determined to conceal.

A year later, they’re both studying at Trinity College in Dublin. Marianne has found her feet in a new social world while Connell hangs at the sidelines, shy and uncertain. Throughout their years in college, Marianne and Connell circle one another, straying toward other people and possibilities but always magnetically, irresistibly drawn back together. Then, as she veers into self-destruction and he begins to search for meaning elsewhere, each must confront how far they are willing to go to save the other.

Sally Rooney brings her brilliant psychological acuity and perfectly spare prose to a story that explores the subtleties of class, the electricity of first love, and the complex entanglements of family and friendship.', '2018-08-28', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1571423190i/41057294.jpg'),
    ('Beautiful World, Where Are You', 'Alice, a novelist, meets Felix, who works in a warehouse, and asks him if he’d like to travel to Rome with her. In Dublin, her best friend, Eileen, is getting over a break-up and slips back into flirting with Simon, a man she has known since childhood. Alice, Felix, Eileen, and Simon are still young—but life is catching up with them.', '2021-09-07', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1618329605i/56597885.jpg'),
    ('The Singing Trees', 'A young artist forges a path of self-discovery in an enriching novel about forgiving the past and embracing second chances, from the bestselling author of An Unfinished Story.

Maine, 1969. After losing her parents in a car accident, aspiring artist Annalisa Mancuso lives with her grandmother and their large Italian family in the stifling factory town of Payton Mills. Inspired by her mother, whose own artistic dreams disappeared in a damaged marriage, Annalisa is dedicated only to painting. Closed off to love, and driven as much by her innate talent as she is the disillusionment of her past, Annalisa just wants to come into her own.', '2021-08-03', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1624661795i/56806042.jpg'),
    ('A Quiet Life', 'Set in a close-knit Pennsylvania suburb in the grip of winter, A Quiet Life follows three people grappling with loss and finding a tender wisdom in their grief.

Chuck Ayers used to look forward to nothing so much as his annual trip to Hilton Head with his wife, Cat—that yearly taste of relaxation they’d become accustomed to in retirement, after a lifetime of working and raising two children. Now, just months after Cat’s death, Chuck finds that he can’t let go of her things—her favorite towel, the sketchbooks in her desk drawer—as he struggles to pack for a trip he can’t imagine taking without her.

Ella Burke delivers morning newspapers and works at a bridal shop to fill her days while she anxiously awaits news—any piece of information—about her missing daughter. Ella adjusts to life in a new apartment and answers every call on her phone, hoping her daughter will reach out one day.

After the sudden death of her father, Kirsten Bonato set aside her veterinary school aspirations, finding comfort in the steady routine of working at an animal shelter. But as time passes, old dreams and new romantic interests begin to surface—and Kirsten finds herself at another crossroads.', '2022-11-29', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1667415143i/60321484.jpg'),
    ('A Man Called Ove', 'A grumpy yet loveable man finds his solitary world turned on its head when a boisterous young family moves in next door.

Meet Ove. He\'s a curmudgeon, the kind of man who points at people he dislikes as if they were burglars caught outside his bedroom window. He has staunch principles, strict routines, and a short fuse. People call him the bitter neighbor from hell, but must Ove be bitter just because he doesn\'t walk around with a smile plastered to his face all the time?

Behind the cranky exterior there is a story and a sadness. So when one November morning a chatty young couple with two chatty young daughters move in next door and accidentally flatten Ove\'s mailbox, it is the lead-in to a comical and heartwarming tale of unkempt cats, unexpected friendship, and the ancient art of backing up a U-Haul. All of which will change one cranky old man and a local residents\' association to their very foundations.', '2012-08-27', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1405259930i/18774964.jpg'),
    ('Anxious People', 'Viewing an apartment normally doesn’t turn into a life-or-death situation, but this particular open house becomes just that when a failed bank robber bursts in and takes everyone in the apartment hostage. As the pressure mounts, the eight strangers begin slowly opening up to one another and reveal long-hidden truths.

First is Zara, a wealthy bank director who has been too busy to care about anyone else until tragedy changed her life. Now, she’s obsessed with visiting open houses to see how ordinary people live—and, perhaps, to set an old wrong to right. Then there’s Roger and Anna-Lena, an Ikea-addicted retired couple who are on a never-ending hunt for fixer-uppers to hide the fact that they don’t know how to fix their own failing marriage. Julia and Ro are a young lesbian couple and soon-to-be parents who are nervous about their chances for a successful life together since they can’t agree on anything. And there’s Estelle, an eighty-year-old woman who has lived long enough to be unimpressed by a masked bank robber waving a gun in her face. And despite the story she tells them all, Estelle hasn’t really come to the apartment to view it for her daughter, and her husband really isn’t outside parking the car.

As police surround the premises and television channels broadcast the hostage situation live, the tension mounts and even deeper secrets are slowly revealed. Before long, the robber must decide which is the more terrifying prospect: going out to face the police, or staying in the apartment with this group of impossible people.', '2019-04-25', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1594234890i/53799686.jpg'),
    ('Beartown', 'People say Beartown is finished. A tiny community nestled deep in the forest, it is slowly losing ground to the ever encroaching trees. But down by the lake stands an old ice rink, built generations ago by the working men who founded this town. And in that ice rink is the reason people in Beartown believe tomorrow will be better than today. Their junior ice hockey team is about to compete in the national semi-finals, and they actually have a shot at winning. All the hopes and dreams of this place now rest on the shoulders of a handful of teenage boys.

Being responsible for the hopes of an entire town is a heavy burden, and the semi-final match is the catalyst for a violent act that will leave a young girl traumatized and a town in turmoil. Accusations are made and, like ripples on a pond, they travel through all of Beartown, leaving no resident unaffected.

Beartown explores the hopes that bring a small community together, the secrets that tear it apart, and the courage it takes for an individual to go against the grain. In this story of a small forest town, Fredrik Backman has found the entire world.', '2016-09-15', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1482108618i/33413128.jpg'),
    ('Us Against You', 'After everything that the citizens of Beartown have gone through, they are struck yet another blow when they hear that their beloved local hockey team will soon be disbanded. What makes it worse is the obvious satisfaction that all the former Beartown players, who now play for a rival team in Hed, take in that fact. Amidst the mounting tension between the two rivals, a surprising newcomer is handpicked to be Beartown’s new hockey coach.

Soon a new team starts to take shape around Amat, the fastest player you’ll ever see; Benji, the intense lone wolf; and Vidar, a born-to-be-bad troublemaker. But bringing this team together proves to be a challenge as old bonds are broken, new ones are formed, and the enmity with Hed grows more and more acute.

As the big match approaches, the not-so-innocent pranks and incidents between the communities pile up and their mutual contempt grows deeper. By the time the last game is finally played, a resident of Beartown will be dead, and the people of both towns will be forced to wonder if, after all they’ve been through, the game they love can ever return to something simple and innocent.', '2017-08-21', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1516019348i/36373463.jpg'),
    ('Britt-Marie Was Here', 'Britt-Marie can’t stand mess. A disorganized cutlery drawer ranks high on her list of unforgivable sins. She is not one to judge others—no matter how ill-mannered, unkempt, or morally suspect they might be. It’s just that sometimes people interpret her helpful suggestions as criticisms, which is certainly not her intention. But hidden inside the socially awkward, fussy busybody is a woman who has more imagination, bigger dreams, and a warmer heart that anyone around her realizes.', '2014-10-03', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1460442061i/27406704.jpg'),
    ('The Winners', 'Two years have passed since the events that no one wants to think about. Everyone has tried to move on, but there’s something about this place that prevents it. The residents continue to grapple with life’s big questions: What is a family? What is a community? And what, if anything, are we willing to sacrifice in order to protect them?

As the locals of Beartown struggle to overcome the past, great change is on the horizon. Someone is coming home after a long time away. Someone will be laid to rest. Someone will fall in love, someone will try to fix their marriage, and someone will do anything to save their children. Someone will submit to hate, someone will fight, and someone will grab a gun and walk towards the ice rink.

So what are the residents of Beartown willing to sacrifice for their home?

Everything.', '2021-10-06', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1645483248i/60318890.jpg')

