INSERT INTO authors (name, surname, biography, photo)
VALUES
    ('Louise','Penny','LOUISE PENNY is the author of the #1 New York Times and Globe and Mail bestselling series of Chief Inspector Armand Gamache novels. She has won numerous awards, including a CWA Dagger and the Agatha Award (seven times), and was a finalist for the Edgar Award for Best Novel. In 2017, she received the Order of Canada for her contributions to Canadian culture. Louise lives in a small village south of Montréal.','https://images.gr-assets.com/authors/1591027995p5/194243.jpg'),
    ('Geraldine', 'Brooks', 'Australian-born Geraldine Brooks is an author and journalist who grew up in the Western suburbs of Sydney, and attended Bethlehem College Ashfield and the University of Sydney. She worked as a reporter for The Sydney Morning Herald for three years as a feature writer with a special interest in environmental issues.

In 1982 she won the Greg Shackleton Australian News Correspondents scholarship to the journalism master’s program at Columbia University in New York City. Later she worked for The Wall Street Journal, where she covered crises in the the Middle East, Africa, and the Balkans.

She was awarded the Pulitzer Prize in fiction in 2006 for her novel March. Her first novel, Year of Wonders, is an international bestseller, and People of the Book is a New York Times bestseller translated into 20 languages. She is also the author of the nonfiction works Nine Parts of Desire and Foreign Correspondence.

Brooks married author Tony Horwitz in Tourette-sur-Loup, France, in 1984. They have two sons– Nathaniel and Bizuayehu–and two dogs. They divide their time between homes in Martha’s Vineyard, Massachusetts, and Sydney, Australia. ', 'https://images.gr-assets.com/authors/1303284528p5/211268.jpg'),
    ('Katy', 'Hays', 'Katy Hays is a writer and adjunct art history professor in California, where she teaches
rural students from Truckee to Tecopa. She holds an MA in art history from Williams
College and pursued her PhD at UC Berkeley. Having previously worked at major art
institutions, including The Clark Art Institute and SF MoMA, she now lives with her
husband and their dog, Queso, in Olympic Valley, California.', 'https://images.gr-assets.com/authors/1655124298p5/21851153.jpg'),
    ('Kevin', 'Wilson', 'Kevin Wilson is the author of two collections, Tunneling to the Center of the Earth (Ecco/Harper Perennial, 2009), which received an Alex Award from the American Library Association and the Shirley Jackson Award, and Baby You’re Gonna Be Mine (Ecco, 2018), and three novels, The Family Fang (Ecco, 2011), Perfect Little World (Ecco, 2017) and Nothing to See Here (Ecco, 2019), a New York Times bestseller and a Read with Jenna book club selection.
His new novel, Now is Not the Time to Panic, will be published by Ecco in November of 2022.', 'https://images.gr-assets.com/authors/1651505988p5/73187.jpg'),
    ('George', 'Orwell', 'Eric Arthur Blair, better known by his pen name George Orwell, was an English author and journalist. His work is marked by keen intelligence and wit, a profound awareness of social injustice, an intense opposition to totalitarianism, a passion for clarity in language, and a belief in democratic socialism.

In addition to his literary career Orwell served as a police officer with the Indian Imperial Police in Burma from 1922-1927 and fought with the Republicans in the Spanish Civil War from 1936-1937. Orwell was severely wounded when he was shot through his throat. Later the organization that he had joined when he joined the Republican cause, The Workers Party of Marxist Unification (POUM), was painted by the pro-Soviet Communists as a Trotskyist organization (Trotsky was Joseph Stalin\'s enemy) and disbanded. Orwell and his wife were accused of "rabid Trotskyism" and tried in absentia in Barcelona, along with other leaders of the POUM, in 1938. However by then they had escaped from Spain and returned to England.

Orwell is best known for the dystopian novel Nineteen Eighty-Four (published in 1949) and the satirical novella Animal Farm (1945) — they have together sold more copies than any two books by any other twentieth-century author. His 1938 book Homage to Catalonia, an account of his experiences as a volunteer on the Republican side during the Spanish Civil War, together with numerous essays on politics, literature, language, and culture, have been widely acclaimed.', 'https://images.gr-assets.com/authors/1588856560p5/3706.jpg'),
    ('F. Scott', 'Fitzgerald', 'Francis Scott Key Fitzgerald was an American writer of novels and short stories, whose works have been seen as evocative of the Jazz Age, a term he himself allegedly coined. He is regarded as one of the greatest twentieth century writers. Fitzgerald was of the self-styled "Lost Generation," Americans born in the 1890s who came of age during World War I. He finished four novels, left a fifth unfinished, and wrote dozens of short stories that treat themes of youth, despair, and age. He was married to Zelda Fitzgerald.', 'https://images.gr-assets.com/authors/1517864008p5/3190.jpg' ),
    ('Jane', 'Austen', 'Jane Austen was an English novelist whose works of romantic fiction, set among the landed gentry, earned her a place as one of the most widely read writers in English literature, her realism and biting social commentary cementing her historical importance among scholars and critics.
Austen\'s works critique the novels of sensibility of the second half of the 18th century and are part of the transition to 19th-century realism. Her plots, though fundamentally comic, highlight the dependence of women on marriage to secure social standing and economic security. Her work brought her little personal fame and only a few positive reviews during her lifetime, but the publication in 1869 of her nephew\'s A Memoir of Jane Austen introduced her to a wider public, and by the 1940s she had become widely accepted in academia as a great English writer. The second half of the 20th century saw a proliferation of Austen scholarship and the emergence of a Janeite fan culture.', 'https://images.gr-assets.com/authors/1651510251p5/1265.jpg'),
    ('Oscar', 'Wilde', 'Oscar Fingal O\'Flahertie Wills Wilde was an Irish playwright, poet, and author of numerous short stories, and one novel. Known for his biting wit, and a plentitude of aphorisms, he became one of the most successful playwrights of the late Victorian era in London, and one of the greatest celebrities of his day. Several of his plays continue to be widely performed, especially The Importance of Being Earnest.

As the result of a widely covered series of trials, Wilde suffered a dramatic downfall and was imprisoned for two years hard labour after being convicted of "gross indecency" with other men. After Wilde was released from prison he set sail for Dieppe by the night ferry. He never returned to Ireland or Britain, and died in poverty.', 'https://images.gr-assets.com/authors/1673611182p5/3565.jpg'),
    ('John', 'Steinbeck', 'John Steinbeck III was an American writer. He wrote the Pulitzer Prize-winning novel The Grapes of Wrath, published in 1939 and the novella Of Mice and Men, published in 1937. In all, he wrote twenty-five books, including sixteen novels, six non-fiction books and several collections of short stories.

In 1962 Steinbeck received the Nobel Prize for Literature.

Steinbeck grew up in the Salinas Valley region of California, a culturally diverse place of rich migratory and immigrant history. This upbringing imparted a regionalistic flavor to his writing, giving many of his works a distinct sense of place.

In his subsequent novels, Steinbeck found a more authentic voice by drawing upon direct memories of his life in California. Later he used real historical conditions and events in the first half of 20th century America, which he had experienced first-hand as a reporter.

Steinbeck often populated his stories with struggling characters; his works examined the lives of the working class and migrant workers during the Dust Bowl and the Great Depression. His later body of work reflected his wide range of interests, including marine biology, politics, religion, history, and mythology.

One of his last published works was Travels with Charley, a travelogue of a road trip he took in 1960 to rediscover America. He died in 1968 in New York of a heart attack and his ashes are interred in Salinas.', 'https://images.gr-assets.com/authors/1182118389p5/585.jpg'),
    ('Ray', 'Bradbury', 'Ray Douglas Bradbury, American novelist, short story writer, essayist, playwright, screenwriter and poet, was born August 22, 1920 in Waukegan, Illinois. He graduated from a Los Angeles high school in 1938. Although his formal education ended there, he became a "student of life," selling newspapers on L.A. street corners from 1938 to 1942, spending his nights in the public library and his days at the typewriter. He became a full-time writer in 1943, and contributed numerous short stories to periodicals before publishing a collection of them, Dark Carnival, in 1947.

His reputation as a writer of courage and vision was established with the publication of The Martian Chronicles in 1950, which describes the first attempts of Earth people to conquer and colonize Mars, and the unintended consequences. Next came The Illustrated Man and then, in 1953, Fahrenheit 451, which many consider to be Bradbury\'s masterpiece, a scathing indictment of censorship set in a future world where the written word is forbidden. In an attempt to salvage their history and culture, a group of rebels memorize entire works of literature and philosophy as their books are burned by the totalitarian state. Other works include The October Country, Dandelion Wine, A Medicine for Melancholy, Something Wicked This Way Comes, I Sing the Body Electric!, Quicker Than the Eye, and Driving Blind. In all, Bradbury has published more than thirty books, close to 600 short stories, and numerous poems, essays, and plays. His short stories have appeared in more than 1,000 school curriculum "recommended reading" anthologies.

Ray Bradbury\'s work has been included in four Best American Short Story collections. He has been awarded the O. Henry Memorial Award, the Benjamin Franklin Award, the World Fantasy Award for Lifetime Achievement, the Grand Master Award from the Science Fiction Writers of America, the PEN Center USA West Lifetime Achievement Award, among others. In November 2000, the National Book Foundation Medal for Distinguished Contribution to American Letters was conferred upon Mr. Bradbury at the 2000 National Book Awards Ceremony in New York City.', 'https://images.gr-assets.com/authors/1445955959p5/1630.jpg'),
    ('Agatha', 'Christie', 'Dame Agatha Mary Clarissa Christie is the best-selling author of all time. She wrote 66 crime novels and story collections, fourteen plays, and six novels under a pseudonym in Romance. Her books have sold over a billion copies in the English language and a billion in translation. According to Index Translationum, she remains the most-translated individual author, having been translated into at least 103 languages. She is the creator of two of the most enduring figures in crime literature-Hercule Poirot and Miss Jane Marple-and author of The Mousetrap, the longest-running play in the history of modern theatre.

Agatha Mary Clarissa Miller was born in Torquay, Devon, England, U.K., as the youngest of three. The Millers had two other children: Margaret Frary Miller (1879–1950), called Madge, who was eleven years Agatha\'s senior, and Louis Montant Miller (1880–1929), called Monty, ten years older than Agatha.

Before marrying and starting a family in London, she had served in a Devon hospital during the First World War, tending to troops coming back from the trenches. During the First World War, she worked at a hospital as a nurse; later working at a hospital pharmacy, a job that influenced her work, as many of the murders in her books are carried out with poison. During the Second World War, she worked as a pharmacy assistant at University College Hospital, London, acquiring a good knowledge of poisons which feature in many of her novels.

Her first novel, The Mysterious Affair at Styles, came out in 1920. During her first marriage, Agatha published six novels, a collection of short stories, and a number of short stories in magazines.

Christie frequently used familiar settings for her stories. Christie\'s travels with Mallowan contributed background to several of her novels set in the Middle East. Other novels (such as And Then There Were None) were set in and around Torquay, where she was born. Christie\'s 1934 novel Murder on the Orient Express was written in the Hotel Pera Palace in Istanbul, Turkey, the southern terminus of the railway. The hotel maintains Christie\'s room as a memorial to the author. The Greenway Estate in Devon, acquired by the couple as a summer residence in 1938, is now in the care of the National Trust.

Christie often stayed at Abney Hall in Cheshire, which was owned by her brother-in-law, James Watts. She based at least two of her stories on the hall: the short story The Adventure of the Christmas Pudding, and the novel After the Funeral. Abney Hall became Agatha\'s greatest inspiration for country-house life, with all the servants and grandeur which have been woven into her plots.


To honour her many literary works, she was appointed Commander of the Order of the British Empire in the 1956 New Year Honours. The next year, she became the President of the Detection Club.', 'https://images.gr-assets.com/authors/1589991473p5/123715.jpg'),
    ('J. D.', 'Salinger', 'Jerome David Salinger was an American author, best known for his 1951 novel The Catcher in the Rye, as well as his reclusive nature. His last original published work was in 1965; he gave his last interview in 1980. Raised in Manhattan, Salinger began writing short stories while in secondary school, and published several stories in the early 1940s before serving in World War II. In 1948 he published the critically acclaimed story "A Perfect Day for Bananafish" in The New Yorker magazine, which became home to much of his subsequent work. In 1951 Salinger released his novel The Catcher in the Rye, an immediate popular success. His depiction of adolescent alienation and loss of innocence in the protagonist Holden Caulfield was influential, especially among adolescent readers. The novel remains widely read and controversial, selling around 250,000 copies a year.

The success of The Catcher in the Rye led to public attention and scrutiny: Salinger became reclusive, publishing new work less frequently. He followed Catcher with a short story collection, Nine Stories (1953), a collection of a novella and a short story, Franny and Zooey (1961), and a collection of two novellas, Raise High the Roof Beam, Carpenters and Seymour: An Introduction (1963). His last published work, a novella entitled "Hapworth 16, 1924", appeared in The New Yorker on June 19, 1965.

Afterward, Salinger struggled with unwanted attention, including a legal battle in the 1980s with biographer Ian Hamilton, and the release in the late 1990s of memoirs written by two people close to him: Joyce Maynard, an ex-lover; and Margaret Salinger, his daughter. In 1996, a small publisher announced a deal with Salinger to publish "Hapworth 16, 1924" in book form, but amid the ensuing publicity, the release was indefinitely delayed. He made headlines around the globe in June 2009, after filing a lawsuit against another writer for copyright infringement resulting from that writer\'s use of one of Salinger\'s characters from The Catcher in the Rye. Salinger died of natural causes on January 27, 2010, at his home in Cornish, New Hampshire.', 'https://images.gr-assets.com/authors/1288777679p5/819789.jpg'),
    ('Harper', 'Lee', 'Harper Lee, known as Nelle, was born in the Alabama town of Monroeville, the youngest of four children of Amasa Coleman Lee and Frances Cunningham Finch Lee. Her father, a former newspaper editor and proprietor, was a lawyer who served on the state legislature from 1926 to 1938. As a child, Lee was a tomboy and a precocious reader, and enjoyed the friendship of her schoolmate and neighbor, the young Truman Capote.

After graduating from high school in Monroeville, Lee enrolled at the all-female Huntingdon College in Montgomery (1944-45), and then pursued a law degree at the University of Alabama (1945-50), pledging the Chi Omega sorority. While there, she wrote for several student publications and spent a year as editor of the campus humor magazine, "Ramma-Jamma". Though she did not complete the law degree, she studied for a summer in Oxford, England, before moving to New York in 1950, where she worked as a reservation clerk with Eastern Air Lines and BOAC.

Lee continued as a reservation clerk until the late 50s, when she devoted herself to writing. She lived a frugal life, traveling between her cold-water-only apartment in New York to her family home in Alabama to care for her father.

Having written several long stories, Harper Lee located an agent in November 1956. The following month at the East 50th townhouse of her friends Michael Brown and Joy Williams Brown, she received a gift of a year\'s wages with a note: "You have one year off from your job to write whatever you please. Merry Christmas."

Within a year, she had a first draft. Working with J. B. Lippincott & Co. editor Tay Hohoff, she completed To Kill a Mockingbird in the summer of 1959. Published July 11, 1960, the novel was an immediate bestseller and won great critical acclaim, including the Pulitzer Prize for Fiction in 1961. It remains a bestseller with more than 30 million copies in print. In 1999, it was voted "Best Novel of the Century" in a poll by the Library Journal.', 'https://images.gr-assets.com/authors/1593873322p5/1825.jpg'),
    ('Ernest', 'Hemingway', 'Ernest Miller Hemingway was an American author and journalist. His economical and understated style had a strong influence on 20th-century fiction, while his life of adventure and his public image influenced later generations. Hemingway produced most of his work between the mid-1920s and the mid-1950s, and won the Nobel Prize in Literature in 1954. He published seven novels, six short story collections and two non-fiction works. Three novels, four collections of short stories and three non-fiction works were published posthumously. Many of these are considered classics of American literature.', 'https://images.gr-assets.com/authors/1654446435p5/1455.jpg'),
    ('Dani', 'Shapiro', 'Dani Shapiro is the bestselling author of the memoirs Hourglass, Still Writing, Devotion, and Slow Motion, and five novels including Black & White and Family History. She lives with her family in LItchfield County, Connecticut. Her latest memoir, Inheritance, will be published by Knopf in January, 2019.', 'https://images.gr-assets.com/authors/1531841838p5/13932.jpg'),
    ('Ethan', 'Joella', 'Ethan Joella teaches English and psychology at the University of Delaware and specializes in community writing workshops. His work has appeared in River Teeth, The Cimarron Review, The MacGuffin, Delaware Beach Life, and Third Wednesday. He is the author of A Little Hope, which was a Read with Jenna Bonus Selection and A Quiet Life. He lives in Rehoboth Beach, Delaware, with his wife and two daughters.', 'https://images.gr-assets.com/authors/1624467544p5/19962976.jpg'),
    ('Sally', 'Rooney', 'Sally Rooney was born in 1991 and lives in Dublin, where she graduated from Trinity College. Her work has appeared in Granta, The Dublin Review, The White Review, The Stinging Fly, and the Winter Pages anthology.', 'https://images.gr-assets.com/authors/1534007127p5/15860970.jpg'),
    ('Boo', 'Walker', 'Bestselling author Boo Walker initially tapped his creative muse as a songwriter and banjoist in Nashville before working his way west to Washington State, where he bought a gentleman’s farm on the Yakima River. It was there amongst the grapevines and wine barrels that he fell in love with telling stories that now resonate with book clubs around the world. Rich with colorful characters and boundless soul, his novels will leave you with an open heart and a lifted spirit.

Always a wanderer, Boo currently lives in Valencia, Spain with his wife and son. He also writes thrillers under the pen name Benjamin Blackmore. You can find him at boowalker.com and benjaminblackmore.com.', 'https://images.gr-assets.com/authors/1524054750p5/5322167.jpg'),
    ('Fredrik', 'Backman', 'Fredrik Backman is the #1 New York Times bestselling author of A Man Called Ove (soon to be a major motion picture starring Tom Hanks), My Grandmother Asked Me to Tell You She’s Sorry, Britt-Marie Was Here, Beartown, Us Against You, as well as two novellas, And Every Morning the Way Home Gets Longer and Longer and The Deal of a Lifetime. Things My Son Needs to Know About the World, his first work of non-fiction, will be released in the US in May 2019. His books are published in more than forty countries. He lives in Stockholm, Sweden, with his wife and two children.', 'https://images.gr-assets.com/authors/1493098924p5/6485178.jpg')


